name: selenium-tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./test
        run: npm ci

      - name: Run Selenium Tests (mocha + mochawesome)
        working-directory: ./test
        run: npx mocha tests/demoApp/app.test.js --timeout 900000 --reporter mochawesome

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: test/mochawesome-report/mochawesome.html