name: selenium-tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔹 Single step for setup + install
      - name: Setup Node.js 18, install dependencies, and build
        run: |
          echo "🔹 Setting up Node.js 18..."
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v
          npm -v

          echo "📦 Installing dependencies..."
          cd test
          npm ci

          echo "✅ Environment and dependencies ready."

      # 🔹 Separate step for Selenium test execution and Mochawesome
      - name: Run Selenium Tests with Mochawesome
        working-directory: ./test
        run: |
          echo "🚀 Running Selenium tests with Mocha + Mochawesome..."
          npx mocha tests/demoApp/app.test.js --timeout 900000 --reporter mochawesome
          echo "✅ Tests completed."

      # 🔹 Upload full Mochawesome report folder
      - name: 📄 Upload full Mochawesome report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: test/mochawesome-report
